name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Copy Main Site
        run: |
          mkdir -p dist
          touch dist/.nojekyll
          cp -r index.html metrics.js go_salary.svg offer dist/
          echo "gobootcamp.online" > dist/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          cname: gobootcamp.online
          clean: true
