name: Deploy Platform to Yandex Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'platform/**'

jobs:
  deploy:
    name: Deploy to Yandex Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # - name: Run tests
      #   run: |
      #     cd platform
      #     go test ./... -v

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Configure Yandex Cloud access
        run: |
          yc config profile create ci-profile
          echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > sa-key.json
          yc config set service-account-key sa-key.json
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      - name: Login to Yandex Container Registry
        uses: docker/login-action@v2
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./platform
          push: true
          tags: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/platform:${{ github.sha }},cr.yandex/${{ secrets.YC_REGISTRY_ID }}/platform:latest

      - name: Deploy to Serverless Containers
        run: |
          yc serverless container revision deploy \
            --container-name app \
            --image cr.yandex/${{ secrets.YC_REGISTRY_ID }}/platform:${{ github.sha }} \
            --service-account-id ${{ secrets.YC_SA_ID }} \
            --cores 1 \
            --memory 512MB \
            --concurrency 5 \
            --execution-timeout 30s \
            --service-id ${{ secrets.YC_SERVICE_ID }} 